config/routes.rb
Rails.application.routes.draw do
  root 'clients#index'



  get'/about', to:'static_clients#about'

  resources :clients
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
class Client < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  def index
    @clients = Client.all;
  end

  def show
    @client = Client.find(params[:id])
  end

  def new
    @client = Client.new
  end

  def create
    @client = Client.new(client_params)

  if @client.save
    redirect_to clients_path
  else
    render :new
  end
 end
  
  def edit
    @client = Client.find(params[:id])
  end

  def update
    @client = Client.find(params[:id])

    if @client.update(client_params)
      redirect_to client_path
    else
      render :edit
    end
  end

  def destroy
    Client.find(params[:id]).destroy
    redirect_to clients_path
  end
end



private

def client_params
  params.require(:client).permit(:name, :hair_color, :eye_color, :gender, :age, :alive)
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/edit.html.erb
<h1>Edit Client</h1>
<%=form_for @client do |f| %>
  
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%=f.label :hair_color %>
  <%=f.text_field :hair_color %>

  <%=f.label :eye_color %>
  <%=f.text_field :eye_color %>

  <%=f.label :gender %>
  <%=f.text_field :gender %>

  <%=f.label :age %>
  <%=f.number_field :age %>

  <%=f.label :alive %>
  <%=f.text_field :alive %>

  <%=f.submit%>
<%end%>

app/views/clients/index.html.erb
<h1>Clients</h1>
<% @clients.each do |client| %>
  <h2><%=client.name %></h2>
  <%=link_to 'Show Client', client_path(client) %>
  <p><%=link_to 'Destroy Client', client, method: :delete %></p>
<% end %>

<h1>New Clients</h1>
<p><%=link_to 'Create Client', new_client_path %></p>



 

app/views/clients/new.html.erb
<h1>New Client</h1>
<%=form_for @client do |f| %>

  <%=f.label :name %>
  <%= f.text_field :name %>

  <%=f.label :hair_color %>
  <%= f.text_field :hair_color %>

  <%=f.label :eye_color %>
  <%= f.text_field :eye_color %>

  <%=f.label :gender %>
  <%= f.text_field :gender %>

  <%=f.label :age %>
  <%= f.text_field :age %>

  <%=f.label :alive %>
  <%= f.text_field :alive %>

  <%=f.submit %>


<% end %>

app/views/clients/show.html.erb
<h1><%=@client.name %></h1>
<h1><%=@client.hair_color %></h1>
<h1><%=@client.eye_color %></h1>
<h1><%=@client.gender %></h1>
<h1><%=@client.age %></h1>
<h1><%=@client.alive%></h1>
<%=link_to'Back', clients_path %>

app/views/layouts/_navbar.html.erb
<%=link_to 'Home', root_path%>
<%=link_to 'About', root_path%>
<%=link_to 'Clients', root_path%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PeopleApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%=render'layouts/navbar'%>
    <%= yield %>
  </body>
</html>